### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by deanmayne** [deanmayne/marcheauxpuces#2]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by mkayys** [comment]
- `Sign In` and `Sign Up` to open the modal need styling
- modals need styling: 
![Screen Shot 2020-12-10 at 6 04 47 PM](https://user-images.githubusercontent.com/48598856/101852322-3c2d8b80-3b12-11eb-93e9-486175ff79a1.png)
- sign up link doesn't work
- can't go to sign up from sign in and vice versa

**Comment by mkayys** [comment]
errors need more styling; no bullet points and consistent font and maybe font color change to red?
![Screen Shot 2020-12-11 at 4 03 44 PM](https://user-images.githubusercontent.com/48598856/101965813-c802ee80-3bca-11eb-8a81-8c9756a6e78d.png)

suggestion to add more to your home page along with products for visual interest (example below):
![Screen Shot 2020-12-11 at 4 08 35 PM](https://user-images.githubusercontent.com/48598856/101965916-2760fe80-3bcb-11eb-8d40-d7e0bacb800a.png)

**Comment by mkayys** [comment]
![Screen Shot 2020-12-16 at 4 14 44 PM](https://user-images.githubusercontent.com/48598856/102421691-e5183280-3fb9-11eb-9134-73d0271517ad.png)
- it's just a little thing but the error message isn't centered
